### ISSUE TITLE
When importing external modules, you should almost never use "from x import *"

### ISSUE THREAD

**Issue by m0xb** [WorryingWonton/QuizGenerator#3]
This is because you might unintentionally bring in a lot of names from that module that you're not aware of. 

Instead, you should import only what you use: `from distutils.util import strtobool`

https://github.com/WorryingWonton/QuizGenerator/blob/ddf181bb35f3802ebe34293ff1eab022a0c61aff/Quiz_Input3.py#L2

**Comment by WorryingWonton** [comment]
Noted and implemented.
